# common configuration for ALL branches

version: '0.9.{build}-beta'  
image: Visual Studio 2017
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - develop
  - master
nuget:  
  disable_publish_on_pr: true
test_script:
- cmd: dotnet restore ./TestCI.Tests/TestCI.Tests.csproj --verbosity m
- cmd: cd TestCI.Tests
- cmd: dotnet xunit -c Release --fx-version 2.0.0

# here we are going to override common configuration
for:

# override settings for `master` branch
# build and publish to MyGet on master commit
# build and publish to NuGet on master tag
-
  branches:  
    only:
    - master
  build_script:  
  - ps: .\build.ps1
  artifacts:  
  - path: .\artifacts\**\*.nupkg
    name: NuGet
  deploy:  
  - provider: NuGet
    server: https://www.myget.org/F/devalp/api/v2/package
    api_key:
      secure: Eg0KDgCo29hYMHnywQRkdU/4r8PdKaGH4LNYAIVBjCc6lrQD1kOrbk8tYMBa41Ur
    skip_symbols: true
    on:
      branch: master
  - provider: NuGet
    name: production
    api_key:
      secure: tO+BGjfWjldA+wN/Du6sTn4n1aF1Ichs6GvFcQDF3Z+TrqMydlBX5VJdJpxJlbDU
    on:
      branch: master
      appveyor_repo_tag: true